from docx import Document
from docx.shared import Inches, Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from typing import List, Dict
import io

class DocxService:
    def generate_im_docx(self, im_data: Dict) -> io.BytesIO:
        doc = Document()
        sections = im_data.get('sections', [])
        sources = im_data.get('sources', [])
        
        # Style Definitions
        style = doc.styles['Normal']
        font = style.font
        font.name = 'Arial'
        font.size = Pt(11)

        # Header
        header = doc.add_heading('Information Memorandum', 0)
        header.alignment = WD_ALIGN_PARAGRAPH.CENTER
        
        doc.add_paragraph('Generated by ProFinance Nexus AI').alignment = WD_ALIGN_PARAGRAPH.CENTER
        doc.add_page_break()

        # Iterate through sections
        for section in sections:
            doc.add_heading(section.get('title', 'Untitled Section'), level=1)
            p = doc.add_paragraph(section.get('content', ''))
            p.alignment = WD_ALIGN_PARAGRAPH.JUSTIFY
            doc.add_paragraph() # Spacer

        # Global References Section (Requirement 7)
        if sources:
            doc.add_page_break()
            doc.add_heading('References', level=1)
            for src in sources:
                p = doc.add_paragraph(style='List Number')
                run = p.add_run(f"{src.get('label')}: ")
                run.bold = True
                p.add_run(src.get('context', ''))

        # Save to buffer
        target = io.BytesIO()
        doc.save(target)
        target.seek(0)
        return target

docx_service = DocxService()
